[package]
name = "freebsd-flatpak"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "flatpak"
path = "src/main.rs"

[[bin]]
name = "freebsd-flatpak-secure-mount"
path = "src/bin/freebsd-flatpak-secure-mount.rs"

[dependencies]
anyhow = "1.0"
base64 = "0.20"
glib = "0.20"
libc = "0.2"
miniz_oxide = "0.8"
ostree = { version = "0.20.5", features = ["v2025_3"] }

[dev-dependencies]
gio = "0.20"
