use anyhow::{bail, Context, Result};
use std::env;
use std::fs;
use std::path::{Component, Path, PathBuf};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AccessMode {
    ReadOnly,
    ReadWrite,
}

impl AccessMode {
    pub fn is_read_only(self) -> bool {
        self == Self::ReadOnly
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::ReadOnly => "read-only",
            Self::ReadWrite => "read-write",
        }
    }
}

#[derive(Debug, Clone)]
pub struct HostPathGrant {
    label: String,
    host_path: PathBuf,
    canonical_host_path: PathBuf,
    sandbox_path: PathBuf,
    access: AccessMode,
}

impl HostPathGrant {
    pub fn new(
        label: impl Into<String>,
        host_path: PathBuf,
        sandbox_path: PathBuf,
        access: AccessMode,
    ) -> Result<Self> {
        if !host_path.is_absolute() {
            bail!(
                "host filesystem grant must be absolute: {}",
                host_path.display()
            );
        }
        if !sandbox_path.is_absolute() {
            bail!(
                "sandbox filesystem grant must be absolute: {}",
                sandbox_path.display()
            );
        }

        let canonical_host_path =
            fs::canonicalize(&host_path).unwrap_or_else(|_| host_path.clone());
        Ok(Self {
            label: label.into(),
            host_path,
            canonical_host_path,
            sandbox_path,
            access,
        })
    }

    pub fn host_path(&self) -> &Path {
        &self.host_path
    }

    pub fn sandbox_path(&self) -> &Path {
        &self.sandbox_path
    }

    pub fn access(&self) -> AccessMode {
        self.access
    }

    pub fn sandbox_target_relative(&self) -> Result<PathBuf> {
        absolute_to_chroot_relative(&self.sandbox_path)
    }

    fn map_host_path(&self, host_path: &Path) -> Option<PathBuf> {
        if let Ok(suffix) = host_path.strip_prefix(&self.host_path) {
            return Some(self.sandbox_path.join(suffix));
        }
        if let Ok(suffix) = host_path.strip_prefix(&self.canonical_host_path) {
            return Some(self.sandbox_path.join(suffix));
        }
        None
    }
}

#[derive(Debug, Clone)]
pub struct HostFilesystem {
    grants: Vec<HostPathGrant>,
}

impl HostFilesystem {
    pub fn default_for_user(user: &str) -> Result<Self> {
        let home = env::var_os("HOME")
            .map(PathBuf::from)
            .context("HOME must be set to derive default host filesystem grants")?;
        let sandbox_home = PathBuf::from("/home").join(user);
        let mut grants = Vec::new();

        for (name, access) in [
            ("Downloads", AccessMode::ReadWrite),
            ("Documents", AccessMode::ReadWrite),
            ("Pictures", AccessMode::ReadOnly),
        ] {
            let host_path = home.join(name);
            if !host_path.is_dir() {
                eprintln!(
                    "warning: not exposing missing host directory {}",
                    host_path.display()
                );
                continue;
            }
            grants.push(HostPathGrant::new(
                name,
                host_path,
                sandbox_home.join(name),
                access,
            )?);
        }

        Ok(Self { grants })
    }

    #[cfg(test)]
    fn new_for_tests(grants: Vec<HostPathGrant>) -> Self {
        Self { grants }
    }

    pub fn grants(&self) -> &[HostPathGrant] {
        &self.grants
    }

    pub fn translate_args(&self, args: &[String]) -> Result<Vec<String>> {
        let mut translated = Vec::new();
        for arg in args {
            if is_standalone_desktop_field_code(arg) {
                continue;
            }

            if arg.starts_with("file://") {
                translated.push(self.translate_file_uri(arg)?);
            } else if looks_like_path_arg(arg) {
                translated.push(self.translate_path_arg(arg)?);
            } else {
                translated.push(arg.clone());
            }
        }
        Ok(translated)
    }

    pub fn write_xdg_user_dirs_config(&self, chroot_root: &Path) -> Result<()> {
        let path = chroot_root
            .join("var")
            .join("config")
            .join("user-dirs.dirs");
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
        }

        let download = self.sandbox_dir_for_label("Downloads", "/var/data/Downloads");
        let documents = self.sandbox_dir_for_label("Documents", "/var/data/Documents");
        let pictures = self.sandbox_dir_for_label("Pictures", "/var/data/Pictures");
        let data = format!(
            "\
# Generated by freebsd-flatpak-poc for this sandbox root.
XDG_DESKTOP_DIR=\"/var/data/Desktop\"
XDG_DOWNLOAD_DIR=\"{download}\"
XDG_TEMPLATES_DIR=\"/var/data/Templates\"
XDG_PUBLICSHARE_DIR=\"/var/data/Public\"
XDG_DOCUMENTS_DIR=\"{documents}\"
XDG_MUSIC_DIR=\"/var/data/Music\"
XDG_PICTURES_DIR=\"{pictures}\"
XDG_VIDEOS_DIR=\"/var/data/Videos\"
"
        );
        fs::write(&path, data).with_context(|| format!("write {}", path.display()))
    }

    pub fn user_dir_env(&self) -> Vec<(String, String)> {
        let mut env = Vec::new();
        for (label, key) in [
            ("Downloads", "XDG_DOWNLOAD_DIR"),
            ("Documents", "XDG_DOCUMENTS_DIR"),
            ("Pictures", "XDG_PICTURES_DIR"),
        ] {
            if let Some(path) = self
                .grants
                .iter()
                .find(|grant| grant.label == label)
                .map(|grant| grant.sandbox_path.display().to_string())
            {
                env.push((key.to_string(), path));
            }
        }
        env
    }

    fn translate_file_uri(&self, arg: &str) -> Result<String> {
        let host_path = local_file_uri_path(arg)?;
        let Some(sandbox_path) = self.map_host_path(&host_path)? else {
            warn_unmapped_file_arg(arg);
            return Ok(arg.to_string());
        };
        Ok(format!("file://{}", percent_encode_path(&sandbox_path)))
    }

    fn translate_path_arg(&self, arg: &str) -> Result<String> {
        let host_path = host_path_from_arg(arg)?;
        let Some(sandbox_path) = self.map_host_path(&host_path)? else {
            warn_unmapped_file_arg(arg);
            return Ok(arg.to_string());
        };
        Ok(sandbox_path.display().to_string())
    }

    fn map_host_path(&self, host_path: &Path) -> Result<Option<PathBuf>> {
        let normalized = normalize_absolute_path(host_path)?;
        let mut best_match: Option<PathBuf> = None;

        for grant in &self.grants {
            if let Some(mapped) = grant.map_host_path(&normalized) {
                let replace = best_match
                    .as_ref()
                    .map(|current| mapped.components().count() > current.components().count())
                    .unwrap_or(true);
                if replace {
                    best_match = Some(mapped);
                }
            }
        }

        Ok(best_match)
    }

    fn sandbox_dir_for_label(&self, label: &str, fallback: &str) -> String {
        self.grants
            .iter()
            .find(|grant| grant.label == label)
            .map(|grant| grant.sandbox_path.display().to_string())
            .unwrap_or_else(|| fallback.to_string())
    }
}

fn absolute_to_chroot_relative(path: &Path) -> Result<PathBuf> {
    if !path.is_absolute() {
        bail!("sandbox path must be absolute: {}", path.display());
    }

    let mut relative = PathBuf::new();
    for component in path.components() {
        match component {
            Component::RootDir => {}
            Component::Normal(part) => relative.push(part),
            Component::CurDir => {}
            _ => bail!("invalid sandbox path: {}", path.display()),
        }
    }

    if relative.as_os_str().is_empty() {
        bail!("refusing to use sandbox root as a mount target");
    }
    Ok(relative)
}

fn local_file_uri_path(uri: &str) -> Result<PathBuf> {
    let rest = uri
        .strip_prefix("file://")
        .context("file URI must start with file://")?;
    let path_part = if let Some(path) = rest.strip_prefix("localhost/") {
        format!("/{path}")
    } else if rest.starts_with('/') {
        rest.to_string()
    } else {
        bail!("unsupported non-local file URI: {uri}");
    };
    let path_part = path_part
        .split_once('#')
        .map(|(path, _)| path)
        .unwrap_or(&path_part)
        .split_once('?')
        .map(|(path, _)| path)
        .unwrap_or(path_part.as_str());
    Ok(PathBuf::from(percent_decode(path_part)?))
}

fn host_path_from_arg(arg: &str) -> Result<PathBuf> {
    if let Some(rest) = arg.strip_prefix("~/") {
        let home = env::var_os("HOME")
            .map(PathBuf::from)
            .context("HOME must be set to expand ~/ file argument")?;
        return Ok(home.join(rest));
    }

    let path = PathBuf::from(arg);
    if path.is_absolute() {
        Ok(path)
    } else {
        Ok(env::current_dir()
            .context("determine current directory for relative file argument")?
            .join(path))
    }
}

fn normalize_absolute_path(path: &Path) -> Result<PathBuf> {
    let absolute = if path.is_absolute() {
        path.to_path_buf()
    } else {
        env::current_dir()
            .context("determine current directory for path normalization")?
            .join(path)
    };

    let mut normalized = PathBuf::new();
    for component in absolute.components() {
        match component {
            Component::RootDir => normalized.push(Path::new("/")),
            Component::Normal(part) => normalized.push(part),
            Component::CurDir => {}
            Component::ParentDir => {
                if normalized != Path::new("/") {
                    normalized.pop();
                }
            }
            _ => bail!("unsupported path component in {}", path.display()),
        }
    }

    if normalized.as_os_str().is_empty() {
        normalized.push(Path::new("/"));
    }
    Ok(normalized)
}

fn looks_like_path_arg(arg: &str) -> bool {
    arg.starts_with('/') || arg.starts_with("./") || arg.starts_with("../") || arg.starts_with("~/")
}

fn is_standalone_desktop_field_code(arg: &str) -> bool {
    matches!(arg, "%f" | "%F" | "%u" | "%U" | "%i" | "%c" | "%k" | "%%")
}

fn warn_unmapped_file_arg(arg: &str) {
    eprintln!(
        "warning: file argument is outside configured host filesystem grants and may not be visible inside sandbox: {arg}"
    );
}

fn percent_decode(value: &str) -> Result<String> {
    let bytes = value.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'%' {
            if index + 2 >= bytes.len() {
                bail!("invalid percent escape in file URI: {value}");
            }
            let hi = hex_value(bytes[index + 1])
                .with_context(|| format!("invalid percent escape in file URI: {value}"))?;
            let lo = hex_value(bytes[index + 2])
                .with_context(|| format!("invalid percent escape in file URI: {value}"))?;
            decoded.push((hi << 4) | lo);
            index += 3;
        } else {
            decoded.push(bytes[index]);
            index += 1;
        }
    }
    String::from_utf8(decoded).context("file URI path is not valid UTF-8")
}

fn percent_encode_path(path: &Path) -> String {
    let text = path.display().to_string();
    let mut encoded = String::new();
    for byte in text.bytes() {
        let keep = byte.is_ascii_alphanumeric() || matches!(byte, b'/' | b'-' | b'_' | b'.' | b'~');
        if keep {
            encoded.push(byte as char);
        } else {
            encoded.push_str(&format!("%{byte:02X}"));
        }
    }
    encoded
}

fn hex_value(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        b'A'..=b'F' => Some(byte - b'A' + 10),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::{AccessMode, HostFilesystem, HostPathGrant};
    use std::path::PathBuf;

    fn test_filesystem() -> HostFilesystem {
        HostFilesystem::new_for_tests(vec![HostPathGrant::new(
            "Documents",
            PathBuf::from("/host/home/user/Documents"),
            PathBuf::from("/home/user/Documents"),
            AccessMode::ReadWrite,
        )
        .unwrap()])
    }

    #[test]
    fn translates_allowed_absolute_path() {
        let fs = test_filesystem();
        let args = fs
            .translate_args(&["/host/home/user/Documents/test.txt".to_string()])
            .unwrap();
        assert_eq!(args, ["/home/user/Documents/test.txt"]);
    }

    #[test]
    fn translates_allowed_file_uri() {
        let fs = test_filesystem();
        let args = fs
            .translate_args(&["file:///host/home/user/Documents/a%20b.txt".to_string()])
            .unwrap();
        assert_eq!(args, ["file:///home/user/Documents/a%20b.txt"]);
    }

    #[test]
    fn drops_literal_desktop_field_codes() {
        let fs = test_filesystem();
        let args = fs
            .translate_args(&["--new-window".to_string(), "%U".to_string()])
            .unwrap();
        assert_eq!(args, ["--new-window"]);
    }
}
